// Claude 记录 → ZCode v4 ConversationRow 的投影器。
// 历史（getSessionMessages 读出的 JSONL 记录）与实时（SDK query() 流出的消息）共用这一份逻辑：
// 两者的 user/assistant 记录都是 Anthropic Messages 形态，实时流额外有 stream_event 与 result。
import type {
  AssistantTextRow,
  ConversationRow,
  ReasoningRow,
  TimelineMarkerRow,
  ToolCallRow,
  TurnHeaderRow,
  UserInputRow,
} from "@zcode/shared/zcode-protocol-v4";
import {
  isRecord,
  parseTime,
  RowProjectorBase,
  truncate,
  type JsonRecord,
} from "../rowProjectorBase.js";


/** getSessionMessages 与 SDKMessage 的公共子集；只按需读取字段。 */
export interface ClaudeRecord {
  type: string;
  subtype?: string;
  uuid?: string;
  timestamp?: string;
  isMeta?: boolean;
  isReplay?: boolean;
  isCompletedLocalCommand?: boolean;
  parent_tool_use_id?: string | null;
  message?: unknown;
  event?: unknown;
  [key: string]: unknown;
}

const INTERRUPT_MARKERS = ["[Request interrupted by user", "doesn't want to proceed with this tool use"];



function toolResultText(content: unknown): string {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return "";
  const parts: string[] = [];
  for (const block of content) {
    if (!isRecord(block)) continue;
    if (block.type === "text" && typeof block.text === "string") parts.push(block.text);
    else if (block.type === "image") parts.push("[图片]");
  }
  return parts.join("\n");
}


/** 解析 Claude Code 的斜杠命令包装：`<command-name>/model</command-name>…<command-args>x</command-args>` */
function parseSlashCommand(text: string): string | null {
  const name = /<command-name>([^<]*)<\/command-name>/.exec(text)?.[1]?.trim();
  if (!name) return null;
  const args = /<command-args>([\s\S]*?)<\/command-args>/.exec(text)?.[1]?.trim();
  return args ? `${name} ${args}` : name;
}

/** 不应作为用户气泡展示的注入文本。 */
function isInjectedUserText(text: string): boolean {
  const trimmed = text.trimStart();
  return (
    trimmed.startsWith("<local-command-stdout>") ||
    trimmed.startsWith("<local-command-stderr>") ||
    trimmed.startsWith("<local-command-caveat>") ||
    trimmed.startsWith("<system-reminder>") ||
    trimmed.startsWith("<task-notification>") ||
    trimmed.startsWith("Caveat: The messages below were generated by the user")
  );
}

interface StreamQueue {
  text: number[];
  thinking: number[];
  textCursor: number;
  thinkingCursor: number;
}
export class ClaudeRowProjector extends RowProjectorBase {
  private streamMessageId: string | null = null;
  private readonly streamBlocks = new Map<number, number>();
  private readonly streamQueues = new Map<string, StreamQueue>();

  protected override onTurnClosed() {
    this.streamBlocks.clear();
    this.streamMessageId = null;
  }

  // ───────────────────────── 记录消费 ─────────────────────────

  consume(record: ClaudeRecord, now = Date.now()) {
    // v1 不展开子 agent 内部过程，只看主线程。
    if (record.parent_tool_use_id) return;
    const at = parseTime(record.timestamp, now);
    switch (record.type) {
      case "user":
        this.consumeUser(record, at);
        break;
      case "assistant":
        this.consumeAssistant(record, at);
        break;
      case "stream_event":
        this.consumeStreamEvent(record.event, at);
        break;
      case "system":
        this.consumeSystem(record, at);
        break;
      case "result":
        this.consumeResult(record, at);
        break;
      default:
        break;
    }
  }

  private consumeUser(record: ClaudeRecord, at: number) {
    if (record.isReplay || record.isMeta) return;
    const message = isRecord(record.message) ? record.message : null;
    const content = message?.content;

    if (typeof content === "string") {
      this.consumeUserText(content, at, record);
      return;
    }
    if (!Array.isArray(content)) return;

    let hasToolResult = false;
    const texts: string[] = [];
    for (const block of content) {
      if (!isRecord(block)) continue;
      if (block.type === "tool_result") {
        hasToolResult = true;
        this.consumeToolResult(block, at);
      } else if (block.type === "text" && typeof block.text === "string") {
        texts.push(block.text);
      } else if (block.type === "image") {
        texts.push("[图片]");
      }
    }
    // 与 tool_result 同条出现的文字是运行时注入（提醒等），不当作用户输入。
    if (!hasToolResult && texts.length > 0) {
      this.consumeUserText(texts.join("\n"), at, record);
    }
  }

  private consumeUserText(text: string, at: number, record: ClaudeRecord) {
    if (INTERRUPT_MARKERS.some((marker) => text.startsWith(marker))) {
      this.interrupted = true;
      return;
    }
    if (isInjectedUserText(text)) return;
    const command = parseSlashCommand(text);
    if (command) {
      this.beginUserTurn(command, at, record.uuid);
      return;
    }
    if (!text.trim()) return;
    this.beginUserTurn(text, at, record.uuid);
  }

  private consumeToolResult(block: JsonRecord, at: number) {
    const toolUseId = typeof block.tool_use_id === "string" ? block.tool_use_id : "";
    const rowId = this.toolRows.get(toolUseId);
    if (rowId === undefined) return;
    const text = truncate(toolResultText(block.content));
    const isError = block.is_error === true;
    // 用户在审批卡片上拒绝过的工具，Claude 回传的 tool_result 也是 is_error，保持“已取消”
    const alreadyCancelled = (this.rows.get(rowId) as ToolCallRow | undefined)?.status === "cancelled";
    const cancelled =
      isError && (alreadyCancelled || INTERRUPT_MARKERS.some((marker) => text.includes(marker)));
    this.ensureTurn(at);
    this.patch<ToolCallRow>(rowId, (row) => {
      const { approvalInteractionId: _approval, ...rest } = row;
      return {
        ...rest,
        status: cancelled ? "cancelled" : isError ? "error" : "success",
        output: { text },
        ...(isError && !cancelled ? { error: { code: "tool_error", message: text } } : {}),
        endedAt: at,
      };
    });
  }

  private consumeAssistant(record: ClaudeRecord, at: number) {
    const message = isRecord(record.message) ? record.message : null;
    if (!message || !Array.isArray(message.content)) return;
    const messageId = typeof message.id === "string" ? message.id : undefined;
    const model = typeof message.model === "string" ? message.model : undefined;
    this.ensureTurn(at);
    for (const block of message.content) {
      if (!isRecord(block)) continue;
      switch (block.type) {
        case "text":
          this.finalizeTextBlock("text", messageId, typeof block.text === "string" ? block.text : "", model, at);
          break;
        case "thinking":
          this.finalizeTextBlock(
            "thinking",
            messageId,
            typeof block.thinking === "string" ? block.thinking : "",
            model,
            at,
          );
          break;
        case "tool_use":
        case "server_tool_use": {
          const id = typeof block.id === "string" ? block.id : `tool-${this.nextRowId}`;
          const name = typeof block.name === "string" ? block.name : "tool";
          const input = isRecord(block.input) ? block.input : {};
          const existing = this.toolRows.get(id);
          if (existing === undefined) {
            this.createToolRow(id, name, input, at, block.type === "server_tool_use" ? "success" : "running");
          } else {
            this.patch<ToolCallRow>(existing, (row) => ({
              ...row,
              toolName: name,
              input,
              inputText: JSON.stringify(input),
              status: row.status === "inputStreaming" ? "running" : row.status,
            }));
          }
          break;
        }
        default:
          break;
      }
    }
  }

  private queueFor(messageId: string): StreamQueue {
    let queue = this.streamQueues.get(messageId);
    if (!queue) {
      queue = { text: [], thinking: [], textCursor: 0, thinkingCursor: 0 };
      this.streamQueues.set(messageId, queue);
    }
    return queue;
  }

  /** 完整 assistant 消息到达：优先覆盖对应的流式行，没有流式行时新建。 */
  private finalizeTextBlock(
    kind: "text" | "thinking",
    messageId: string | undefined,
    text: string,
    model: string | undefined,
    at: number,
  ) {
    let streamedRowId: number | undefined;
    if (messageId) {
      const queue = this.queueFor(messageId);
      if (kind === "text") streamedRowId = queue.text[queue.textCursor++];
      else streamedRowId = queue.thinking[queue.thinkingCursor++];
    }
    if (streamedRowId !== undefined) {
      if (kind === "text") {
        this.patch<AssistantTextRow>(streamedRowId, (row) => ({
          ...row,
          text: text || row.text,
          state: "complete",
          ...(model ? { model } : {}),
        }));
      } else {
        this.patch<ReasoningRow>(streamedRowId, (row) => ({
          ...row,
          text: text || row.text,
          state: "complete",
          durationMs: Math.max(0, at - row.createdAt),
        }));
      }
      return;
    }
    if (!text.trim()) return;
    if (kind === "text") {
      const row: AssistantTextRow = {
        ...this.base(at),
        kind: "assistantText",
        text,
        state: "complete",
        ...(messageId ? { assistantResponseId: messageId } : {}),
        ...(model ? { model } : {}),
      };
      this.put(row);
    } else {
      const row: ReasoningRow = {
        ...this.base(at),
        kind: "reasoning",
        text,
        state: "complete",
        ...(messageId ? { assistantResponseId: messageId } : {}),
      };
      this.put(row);
    }
  }

  private consumeStreamEvent(event: unknown, at: number) {
    if (!isRecord(event)) return;
    switch (event.type) {
      case "message_start": {
        const message = isRecord(event.message) ? event.message : null;
        this.streamMessageId = typeof message?.id === "string" ? message.id : null;
        this.streamBlocks.clear();
        break;
      }
      case "content_block_start": {
        const index = typeof event.index === "number" ? event.index : -1;
        const block = isRecord(event.content_block) ? event.content_block : null;
        if (!block) break;
        this.ensureTurn(at);
        const messageId = this.streamMessageId;
        if (block.type === "text" || block.type === "thinking") {
          const row: AssistantTextRow | ReasoningRow =
            block.type === "text"
              ? {
                  ...this.base(at),
                  kind: "assistantText",
                  text: typeof block.text === "string" ? block.text : "",
                  state: "streaming",
                  ...(messageId ? { assistantResponseId: messageId } : {}),
                }
              : {
                  ...this.base(at),
                  kind: "reasoning",
                  text: typeof block.thinking === "string" ? block.thinking : "",
                  state: "streaming",
                  ...(messageId ? { assistantResponseId: messageId } : {}),
                };
          this.put(row);
          this.streamBlocks.set(index, row.rowId);
          if (messageId) {
            const queue = this.queueFor(messageId);
            (block.type === "text" ? queue.text : queue.thinking).push(row.rowId);
          }
        } else if (block.type === "tool_use" || block.type === "server_tool_use") {
          const id = typeof block.id === "string" ? block.id : `tool-${this.nextRowId}`;
          const name = typeof block.name === "string" ? block.name : "tool";
          if (!this.toolRows.has(id)) {
            const rowId = this.createToolRow(id, name, undefined, at, "inputStreaming");
            this.streamBlocks.set(index, rowId);
          }
        }
        break;
      }
      case "content_block_delta": {
        const index = typeof event.index === "number" ? event.index : -1;
        const rowId = this.streamBlocks.get(index);
        const delta = isRecord(event.delta) ? event.delta : null;
        if (rowId === undefined || !delta) break;
        if (delta.type === "text_delta" && typeof delta.text === "string") {
          this.append(rowId, "text", delta.text);
        } else if (delta.type === "thinking_delta" && typeof delta.thinking === "string") {
          this.append(rowId, "text", delta.thinking);
        } else if (delta.type === "input_json_delta" && typeof delta.partial_json === "string") {
          this.append(rowId, "inputText", delta.partial_json);
        }
        if (this.turn) this.turn.lastAt = at;
        break;
      }
      default:
        break;
    }
  }

  private consumeSystem(record: ClaudeRecord, at: number) {
    const subtype =
      record.subtype ?? (isRecord(record.message) && typeof record.message.subtype === "string"
        ? record.message.subtype
        : undefined);
    if (subtype === "compact_boundary") {
      this.ensureTurn(at);
      const row: TimelineMarkerRow = {
        ...this.base(at),
        kind: "timelineMarker",
        lane: "assistantWork",
        marker: { type: "compact", origin: "auto", status: "success" },
      };
      this.put(row);
    }
  }

  private consumeResult(record: ClaudeRecord, at: number) {
    const subtype = record.subtype;
    const isError = record.is_error === true;
    const duration = typeof record.duration_ms === "number" ? record.duration_ms : undefined;
    if (!this.turn) return;
    if (isError && !this.interrupted) {
      const message =
        typeof record.result === "string" && record.result
          ? record.result
          : Array.isArray(record.errors)
            ? record.errors.join("\n")
            : `Claude 执行出错（${subtype ?? "unknown"}）`;
      const row: AssistantTextRow = {
        ...this.base(at),
        kind: "assistantText",
        text: message,
        state: "failed",
      };
      this.put(row);
      this.closeTurn(at, "failed", duration);
      return;
    }
    this.closeTurn(at, undefined, duration);
  }
}

/** 历史记录一次性投影成行。 */
export function projectHistory(records: readonly ClaudeRecord[]): ClaudeRowProjector {
  const projector = new ClaudeRowProjector();
  let lastAt = 0;
  for (const record of records) {
    projector.consume(record);
    lastAt = Math.max(lastAt, parseTime(record.timestamp, lastAt));
  }
  projector.closeTurn(lastAt || Date.now());
  projector.drain();
  return projector;
}
