// Claude 记录 → ZCode v4 ConversationRow 的投影器。
// 历史（getSessionMessages 读出的 JSONL 记录）与实时（SDK query() 流出的消息）共用这一份逻辑：
// 两者的 user/assistant 记录都是 Anthropic Messages 形态，实时流额外有 stream_event 与 result。
import type {
  AssistantTextRow,
  ConversationRow,
  ReasoningRow,
  TimelineMarkerRow,
  ToolCallRow,
  TurnHeaderRow,
  UserInputRow,
} from "@zcode/shared/zcode-protocol-v4";
import type { RowOp } from "../../../shared/types.js";

type JsonRecord = Record<string, unknown>;

/** getSessionMessages 与 SDKMessage 的公共子集；只按需读取字段。 */
export interface ClaudeRecord {
  type: string;
  subtype?: string;
  uuid?: string;
  timestamp?: string;
  isMeta?: boolean;
  isReplay?: boolean;
  isCompletedLocalCommand?: boolean;
  parent_tool_use_id?: string | null;
  message?: unknown;
  event?: unknown;
  [key: string]: unknown;
}

const MAX_TOOL_OUTPUT_CHARS = 60_000;
const INTERRUPT_MARKERS = ["[Request interrupted by user", "doesn't want to proceed with this tool use"];

function isRecord(value: unknown): value is JsonRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function parseTime(value: unknown, fallback: number): number {
  if (typeof value === "string") {
    const parsed = Date.parse(value);
    if (Number.isFinite(parsed)) return parsed;
  }
  return fallback;
}

function toolResultText(content: unknown): string {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return "";
  const parts: string[] = [];
  for (const block of content) {
    if (!isRecord(block)) continue;
    if (block.type === "text" && typeof block.text === "string") parts.push(block.text);
    else if (block.type === "image") parts.push("[图片]");
  }
  return parts.join("\n");
}

function truncate(text: string): string {
  return text.length > MAX_TOOL_OUTPUT_CHARS
    ? `${text.slice(0, MAX_TOOL_OUTPUT_CHARS)}\n…（输出过长，已截断）`
    : text;
}

/** 解析 Claude Code 的斜杠命令包装：`<command-name>/model</command-name>…<command-args>x</command-args>` */
function parseSlashCommand(text: string): string | null {
  const name = /<command-name>([^<]*)<\/command-name>/.exec(text)?.[1]?.trim();
  if (!name) return null;
  const args = /<command-args>([\s\S]*?)<\/command-args>/.exec(text)?.[1]?.trim();
  return args ? `${name} ${args}` : name;
}

/** 不应作为用户气泡展示的注入文本。 */
function isInjectedUserText(text: string): boolean {
  const trimmed = text.trimStart();
  return (
    trimmed.startsWith("<local-command-stdout>") ||
    trimmed.startsWith("<local-command-stderr>") ||
    trimmed.startsWith("<local-command-caveat>") ||
    trimmed.startsWith("<system-reminder>") ||
    trimmed.startsWith("<task-notification>") ||
    trimmed.startsWith("Caveat: The messages below were generated by the user")
  );
}

interface StreamQueue {
  text: number[];
  thinking: number[];
  textCursor: number;
  thinkingCursor: number;
}

export class ClaudeRowProjector {
  private readonly rows = new Map<number, ConversationRow>();
  private readonly order: number[] = [];
  private nextRowId = 1;
  private seq = 0;
  private ops: RowOp[] = [];
  private turn: { turnId: string; headerRowId: number; startedAt: number; lastAt: number } | null =
    null;
  private readonly toolRows = new Map<string, number>();
  private streamMessageId: string | null = null;
  private readonly streamBlocks = new Map<number, number>();
  private readonly streamQueues = new Map<string, StreamQueue>();
  private interrupted = false;
  private turnCounter = 0;

  /** 当前全部行（按 rowId 顺序）。 */
  snapshot(): ConversationRow[] {
    return this.order.map((id) => this.rows.get(id)!).filter(Boolean);
  }

  /** 取出自上次调用以来的增量操作。 */
  drain(): RowOp[] {
    const ops = this.ops;
    this.ops = [];
    return ops;
  }

  get hasOpenTurn(): boolean {
    return this.turn !== null;
  }

  // ───────────────────────── 行的基础操作 ─────────────────────────

  private base(at: number) {
    return {
      rowId: this.nextRowId++,
      turnId: this.turn?.turnId ?? "orphan",
      createdAt: at,
      createdAtSeq: this.seq++,
    };
  }

  private put(row: ConversationRow) {
    if (!this.rows.has(row.rowId)) this.order.push(row.rowId);
    this.rows.set(row.rowId, row);
    this.ops.push({ op: "upsert", row });
  }

  private patch<T extends ConversationRow>(rowId: number, update: (row: T) => T) {
    const row = this.rows.get(rowId) as T | undefined;
    if (!row) return;
    this.put(update(row));
  }

  private append(rowId: number, field: "text" | "inputText", text: string) {
    if (!text) return;
    const row = this.rows.get(rowId) as (ConversationRow & Record<string, unknown>) | undefined;
    if (!row) return;
    const current = typeof row[field] === "string" ? (row[field] as string) : "";
    this.rows.set(rowId, { ...row, [field]: current + text } as ConversationRow);
    this.ops.push({ op: "append", rowId, field, text });
  }

  // ───────────────────────── 轮次 ─────────────────────────

  /** 开启一轮：写 turnHeader + userInput。实时发送与历史里的真实用户消息都走这里。 */
  beginUserTurn(text: string, at: number, turnId?: string) {
    this.closeTurn(at);
    this.interrupted = false;
    const id = turnId ?? `turn-${++this.turnCounter}-${at}`;
    const headerRowId = this.nextRowId;
    this.turn = { turnId: id, headerRowId, startedAt: at, lastAt: at };
    const header: TurnHeaderRow = {
      ...this.base(at),
      kind: "turnHeader",
      origin: "userInput",
      executionKind: "agent",
      state: "running",
      startedAt: at,
    };
    this.put(header);
    const input: UserInputRow = {
      ...this.base(at),
      kind: "userInput",
      origin: "realUser",
      text,
    };
    this.put(input);
  }

  private ensureTurn(at: number) {
    if (!this.turn) this.beginSyntheticTurn(at);
    else this.turn.lastAt = Math.max(this.turn.lastAt, at);
  }

  private beginSyntheticTurn(at: number) {
    const id = `turn-${++this.turnCounter}-${at}`;
    this.turn = { turnId: id, headerRowId: this.nextRowId, startedAt: at, lastAt: at };
    const header: TurnHeaderRow = {
      ...this.base(at),
      kind: "turnHeader",
      origin: "userInput",
      executionKind: "agent",
      state: "running",
      startedAt: at,
    };
    this.put(header);
  }

  /** 结束当前轮：收尾所有仍在流式/运行中的行。 */
  closeTurn(at: number, outcome?: TurnHeaderRow["state"], activeMs?: number) {
    const turn = this.turn;
    if (!turn) return;
    const interrupted = this.interrupted;
    const state: TurnHeaderRow["state"] =
      outcome ?? (interrupted ? "completedInterrupted" : "completedSuccess");
    for (const rowId of this.order) {
      const row = this.rows.get(rowId);
      if (!row || row.turnId !== turn.turnId) continue;
      if ((row.kind === "assistantText" || row.kind === "reasoning") && row.state === "streaming") {
        this.put({ ...row, state: interrupted ? "interrupted" : "complete" } as ConversationRow);
      } else if (
        row.kind === "toolCall" &&
        (row.status === "running" ||
          row.status === "inputStreaming" ||
          row.status === "pendingApproval")
      ) {
        this.put({ ...row, status: "cancelled", endedAt: at });
      }
    }
    const endedAt = Math.max(at, turn.lastAt);
    this.patch<TurnHeaderRow>(turn.headerRowId, (header) => ({
      ...header,
      state,
      endedAt,
      activeMs: activeMs ?? Math.max(0, endedAt - turn.startedAt),
    }));
    this.turn = null;
    this.streamBlocks.clear();
    this.streamMessageId = null;
  }

  markInterrupted() {
    this.interrupted = true;
  }

  /** 实时会话出错时，在当前轮写一条失败提示并结束该轮。 */
  failTurn(message: string, at: number) {
    this.ensureTurn(at);
    const row: AssistantTextRow = {
      ...this.base(at),
      kind: "assistantText",
      text: message,
      state: "failed",
    };
    this.put(row);
    this.closeTurn(at, "failed");
  }

  // ───────────────────────── 审批 ─────────────────────────

  setToolPendingApproval(
    toolUseId: string,
    toolName: string,
    input: Record<string, unknown>,
    interactionId: string,
    at: number,
  ) {
    let rowId = this.toolRows.get(toolUseId);
    if (rowId === undefined) {
      this.ensureTurn(at);
      rowId = this.createToolRow(toolUseId, toolName, input, at, "pendingApproval");
    }
    this.patch<ToolCallRow>(rowId, (row) => ({
      ...row,
      status: "pendingApproval",
      input: row.input ?? input,
      approvalInteractionId: interactionId,
    }));
  }

  resolveToolApproval(toolUseId: string, allowed: boolean) {
    const rowId = this.toolRows.get(toolUseId);
    if (rowId === undefined) return;
    this.patch<ToolCallRow>(rowId, (row) => {
      const { approvalInteractionId: _approval, ...rest } = row;
      if (row.status !== "pendingApproval") return rest;
      return allowed ? { ...rest, status: "running" } : { ...rest, status: "cancelled" };
    });
  }

  // ───────────────────────── 记录消费 ─────────────────────────

  consume(record: ClaudeRecord, now = Date.now()) {
    // v1 不展开子 agent 内部过程，只看主线程。
    if (record.parent_tool_use_id) return;
    const at = parseTime(record.timestamp, now);
    switch (record.type) {
      case "user":
        this.consumeUser(record, at);
        break;
      case "assistant":
        this.consumeAssistant(record, at);
        break;
      case "stream_event":
        this.consumeStreamEvent(record.event, at);
        break;
      case "system":
        this.consumeSystem(record, at);
        break;
      case "result":
        this.consumeResult(record, at);
        break;
      default:
        break;
    }
  }

  private consumeUser(record: ClaudeRecord, at: number) {
    if (record.isReplay || record.isMeta) return;
    const message = isRecord(record.message) ? record.message : null;
    const content = message?.content;

    if (typeof content === "string") {
      this.consumeUserText(content, at, record);
      return;
    }
    if (!Array.isArray(content)) return;

    let hasToolResult = false;
    const texts: string[] = [];
    for (const block of content) {
      if (!isRecord(block)) continue;
      if (block.type === "tool_result") {
        hasToolResult = true;
        this.consumeToolResult(block, at);
      } else if (block.type === "text" && typeof block.text === "string") {
        texts.push(block.text);
      } else if (block.type === "image") {
        texts.push("[图片]");
      }
    }
    // 与 tool_result 同条出现的文字是运行时注入（提醒等），不当作用户输入。
    if (!hasToolResult && texts.length > 0) {
      this.consumeUserText(texts.join("\n"), at, record);
    }
  }

  private consumeUserText(text: string, at: number, record: ClaudeRecord) {
    if (INTERRUPT_MARKERS.some((marker) => text.startsWith(marker))) {
      this.interrupted = true;
      return;
    }
    if (isInjectedUserText(text)) return;
    const command = parseSlashCommand(text);
    if (command) {
      this.beginUserTurn(command, at, record.uuid);
      return;
    }
    if (!text.trim()) return;
    this.beginUserTurn(text, at, record.uuid);
  }

  private consumeToolResult(block: JsonRecord, at: number) {
    const toolUseId = typeof block.tool_use_id === "string" ? block.tool_use_id : "";
    const rowId = this.toolRows.get(toolUseId);
    if (rowId === undefined) return;
    const text = truncate(toolResultText(block.content));
    const isError = block.is_error === true;
    // 用户在审批卡片上拒绝过的工具，Claude 回传的 tool_result 也是 is_error，保持“已取消”
    const alreadyCancelled = (this.rows.get(rowId) as ToolCallRow | undefined)?.status === "cancelled";
    const cancelled =
      isError && (alreadyCancelled || INTERRUPT_MARKERS.some((marker) => text.includes(marker)));
    this.ensureTurn(at);
    this.patch<ToolCallRow>(rowId, (row) => {
      const { approvalInteractionId: _approval, ...rest } = row;
      return {
        ...rest,
        status: cancelled ? "cancelled" : isError ? "error" : "success",
        output: { text },
        ...(isError && !cancelled ? { error: { code: "tool_error", message: text } } : {}),
        endedAt: at,
      };
    });
  }

  private consumeAssistant(record: ClaudeRecord, at: number) {
    const message = isRecord(record.message) ? record.message : null;
    if (!message || !Array.isArray(message.content)) return;
    const messageId = typeof message.id === "string" ? message.id : undefined;
    const model = typeof message.model === "string" ? message.model : undefined;
    this.ensureTurn(at);
    for (const block of message.content) {
      if (!isRecord(block)) continue;
      switch (block.type) {
        case "text":
          this.finalizeTextBlock("text", messageId, typeof block.text === "string" ? block.text : "", model, at);
          break;
        case "thinking":
          this.finalizeTextBlock(
            "thinking",
            messageId,
            typeof block.thinking === "string" ? block.thinking : "",
            model,
            at,
          );
          break;
        case "tool_use":
        case "server_tool_use": {
          const id = typeof block.id === "string" ? block.id : `tool-${this.nextRowId}`;
          const name = typeof block.name === "string" ? block.name : "tool";
          const input = isRecord(block.input) ? block.input : {};
          const existing = this.toolRows.get(id);
          if (existing === undefined) {
            this.createToolRow(id, name, input, at, block.type === "server_tool_use" ? "success" : "running");
          } else {
            this.patch<ToolCallRow>(existing, (row) => ({
              ...row,
              toolName: name,
              input,
              inputText: JSON.stringify(input),
              status: row.status === "inputStreaming" ? "running" : row.status,
            }));
          }
          break;
        }
        default:
          break;
      }
    }
  }

  private createToolRow(
    id: string,
    name: string,
    input: Record<string, unknown> | undefined,
    at: number,
    status: ToolCallRow["status"],
  ): number {
    const row: ToolCallRow = {
      ...this.base(at),
      kind: "toolCall",
      toolCallId: id,
      toolName: name,
      status,
      inputText: input ? JSON.stringify(input) : "",
      ...(input ? { input } : {}),
      startedAt: at,
    };
    this.toolRows.set(id, row.rowId);
    this.put(row);
    return row.rowId;
  }

  private queueFor(messageId: string): StreamQueue {
    let queue = this.streamQueues.get(messageId);
    if (!queue) {
      queue = { text: [], thinking: [], textCursor: 0, thinkingCursor: 0 };
      this.streamQueues.set(messageId, queue);
    }
    return queue;
  }

  /** 完整 assistant 消息到达：优先覆盖对应的流式行，没有流式行时新建。 */
  private finalizeTextBlock(
    kind: "text" | "thinking",
    messageId: string | undefined,
    text: string,
    model: string | undefined,
    at: number,
  ) {
    let streamedRowId: number | undefined;
    if (messageId) {
      const queue = this.queueFor(messageId);
      if (kind === "text") streamedRowId = queue.text[queue.textCursor++];
      else streamedRowId = queue.thinking[queue.thinkingCursor++];
    }
    if (streamedRowId !== undefined) {
      if (kind === "text") {
        this.patch<AssistantTextRow>(streamedRowId, (row) => ({
          ...row,
          text: text || row.text,
          state: "complete",
          ...(model ? { model } : {}),
        }));
      } else {
        this.patch<ReasoningRow>(streamedRowId, (row) => ({
          ...row,
          text: text || row.text,
          state: "complete",
          durationMs: Math.max(0, at - row.createdAt),
        }));
      }
      return;
    }
    if (!text.trim()) return;
    if (kind === "text") {
      const row: AssistantTextRow = {
        ...this.base(at),
        kind: "assistantText",
        text,
        state: "complete",
        ...(messageId ? { assistantResponseId: messageId } : {}),
        ...(model ? { model } : {}),
      };
      this.put(row);
    } else {
      const row: ReasoningRow = {
        ...this.base(at),
        kind: "reasoning",
        text,
        state: "complete",
        ...(messageId ? { assistantResponseId: messageId } : {}),
      };
      this.put(row);
    }
  }

  private consumeStreamEvent(event: unknown, at: number) {
    if (!isRecord(event)) return;
    switch (event.type) {
      case "message_start": {
        const message = isRecord(event.message) ? event.message : null;
        this.streamMessageId = typeof message?.id === "string" ? message.id : null;
        this.streamBlocks.clear();
        break;
      }
      case "content_block_start": {
        const index = typeof event.index === "number" ? event.index : -1;
        const block = isRecord(event.content_block) ? event.content_block : null;
        if (!block) break;
        this.ensureTurn(at);
        const messageId = this.streamMessageId;
        if (block.type === "text" || block.type === "thinking") {
          const row: AssistantTextRow | ReasoningRow =
            block.type === "text"
              ? {
                  ...this.base(at),
                  kind: "assistantText",
                  text: typeof block.text === "string" ? block.text : "",
                  state: "streaming",
                  ...(messageId ? { assistantResponseId: messageId } : {}),
                }
              : {
                  ...this.base(at),
                  kind: "reasoning",
                  text: typeof block.thinking === "string" ? block.thinking : "",
                  state: "streaming",
                  ...(messageId ? { assistantResponseId: messageId } : {}),
                };
          this.put(row);
          this.streamBlocks.set(index, row.rowId);
          if (messageId) {
            const queue = this.queueFor(messageId);
            (block.type === "text" ? queue.text : queue.thinking).push(row.rowId);
          }
        } else if (block.type === "tool_use" || block.type === "server_tool_use") {
          const id = typeof block.id === "string" ? block.id : `tool-${this.nextRowId}`;
          const name = typeof block.name === "string" ? block.name : "tool";
          if (!this.toolRows.has(id)) {
            const rowId = this.createToolRow(id, name, undefined, at, "inputStreaming");
            this.streamBlocks.set(index, rowId);
          }
        }
        break;
      }
      case "content_block_delta": {
        const index = typeof event.index === "number" ? event.index : -1;
        const rowId = this.streamBlocks.get(index);
        const delta = isRecord(event.delta) ? event.delta : null;
        if (rowId === undefined || !delta) break;
        if (delta.type === "text_delta" && typeof delta.text === "string") {
          this.append(rowId, "text", delta.text);
        } else if (delta.type === "thinking_delta" && typeof delta.thinking === "string") {
          this.append(rowId, "text", delta.thinking);
        } else if (delta.type === "input_json_delta" && typeof delta.partial_json === "string") {
          this.append(rowId, "inputText", delta.partial_json);
        }
        if (this.turn) this.turn.lastAt = at;
        break;
      }
      default:
        break;
    }
  }

  private consumeSystem(record: ClaudeRecord, at: number) {
    const subtype =
      record.subtype ?? (isRecord(record.message) && typeof record.message.subtype === "string"
        ? record.message.subtype
        : undefined);
    if (subtype === "compact_boundary") {
      this.ensureTurn(at);
      const row: TimelineMarkerRow = {
        ...this.base(at),
        kind: "timelineMarker",
        lane: "assistantWork",
        marker: { type: "compact", origin: "auto", status: "success" },
      };
      this.put(row);
    }
  }

  private consumeResult(record: ClaudeRecord, at: number) {
    const subtype = record.subtype;
    const isError = record.is_error === true;
    const duration = typeof record.duration_ms === "number" ? record.duration_ms : undefined;
    if (!this.turn) return;
    if (isError && !this.interrupted) {
      const message =
        typeof record.result === "string" && record.result
          ? record.result
          : Array.isArray(record.errors)
            ? record.errors.join("\n")
            : `Claude 执行出错（${subtype ?? "unknown"}）`;
      const row: AssistantTextRow = {
        ...this.base(at),
        kind: "assistantText",
        text: message,
        state: "failed",
      };
      this.put(row);
      this.closeTurn(at, "failed", duration);
      return;
    }
    this.closeTurn(at, undefined, duration);
  }
}

/** 历史记录一次性投影成行。 */
export function projectHistory(records: readonly ClaudeRecord[]): ClaudeRowProjector {
  const projector = new ClaudeRowProjector();
  let lastAt = 0;
  for (const record of records) {
    projector.consume(record);
    lastAt = Math.max(lastAt, parseTime(record.timestamp, lastAt));
  }
  projector.closeTurn(lastAt || Date.now());
  projector.drain();
  return projector;
}
